#!/usr/bin/env python3
"""Web dashboard for MaxText job performance analysis.

Serves a single-page app that lets users browse, compare, and download
analysis results generated by ``analyze_job.py``.

Usage:
    perf_server.py [--host HOST] [--port PORT] [--outputs-dir DIR]

Dependencies:
    pip install fastapi uvicorn
"""

from __future__ import annotations

import argparse
import csv
import io
import json
import re
import subprocess
import sys
import zipfile
from pathlib import Path

from fastapi import FastAPI, HTTPException, Query, Request
from fastapi.responses import (
    FileResponse,
    HTMLResponse,
    JSONResponse,
    StreamingResponse,
)

# ── Setup ────────────────────────────────────────────────────────────────────

SCRIPT_DIR = Path(__file__).resolve().parent
DASHBOARD_HTML = SCRIPT_DIR / "perf_dashboard.html"

app = FastAPI(title="MaxText Perf Dashboard", version="0.1.0")

# Set at startup via configure()
_outputs_dir: Path = SCRIPT_DIR.parent / "outputs"


def configure(outputs_dir: Path) -> None:
    global _outputs_dir
    _outputs_dir = outputs_dir


# ── Helpers ──────────────────────────────────────────────────────────────────


def _scan_jobs() -> list[dict]:
    """Scan outputs directory for jobs with analysis.json."""
    jobs = []
    if not _outputs_dir.is_dir():
        return jobs
    for entry in sorted(_outputs_dir.iterdir()):
        if not entry.is_dir():
            continue
        aj = entry / "analysis.json"
        if aj.is_file():
            try:
                data = json.loads(aj.read_text())
                data["_dir_name"] = entry.name
                data["_dir_path"] = str(entry)
                jobs.append(data)
            except (json.JSONDecodeError, OSError):
                pass
    return jobs


def _find_job_dir(job_id: str) -> Path:
    """Resolve a job_id to its directory. Raises 404 if not found."""
    if not _outputs_dir.is_dir():
        raise HTTPException(404, "Outputs directory not found")
    for entry in sorted(_outputs_dir.iterdir()):
        if entry.is_dir() and entry.name.startswith(f"{job_id}-"):
            return entry
    raise HTTPException(404, f"Job {job_id} not found")


def _load_analysis(job_dir: Path) -> dict:
    """Load analysis.json from a job directory."""
    aj = job_dir / "analysis.json"
    if not aj.is_file():
        raise HTTPException(404, "analysis.json not found — run analyze_job.py first")
    try:
        return json.loads(aj.read_text())
    except (json.JSONDecodeError, OSError) as e:
        raise HTTPException(500, f"Failed to read analysis.json: {e}")


def _find_log_file(job_dir: Path) -> Path | None:
    """Find the log file for this job."""
    log_link = job_dir / "log"
    if log_link.is_file():
        return log_link.resolve()
    parent = job_dir.parent
    m = re.match(r"^([^-]+)-", job_dir.name)
    if m:
        job_id = m.group(1)
        for suffix in (".log", ".out"):
            candidates = sorted(parent.glob(f"{job_id}-*{suffix}"))
            if candidates:
                return candidates[0]
    return None


def _find_hlo_file(job_dir: Path) -> Path | None:
    """Find the latest jit_train_step HLO dump for IRLens."""
    xla_dump = job_dir / "xla_dump"
    if not xla_dump.is_dir():
        return None
    candidates = sorted(xla_dump.glob("*jit_train_step*gpu_after_optimizations.txt"))
    return candidates[-1] if candidates else None


def _logical_steps(tgs: dict, num_nodes: int | None) -> int | None:
    """Return the number of logical training steps (raw count / num_nodes)."""
    all_info = tgs.get("all", {})
    n = all_info.get("n")
    if n is None:
        return None
    nn = num_nodes or 1
    return n // nn


def _job_summary(j: dict, dir_name: str = "", include_per_step: bool = False) -> dict:
    """Build a job summary dict from analysis.json data."""
    tgs = j.get("tgs", {})
    steady = tgs.get("steady")
    tl = j.get("tracelens_summary", {})
    summary = {
        "job_id": j.get("job_id", ""),
        "job_name": j.get("job_name", ""),
        "model": j.get("model", ""),
        "exp_tag": j.get("exp_tag", ""),
        "num_nodes": j.get("num_nodes"),
        "dir_name": dir_name or j.get("_dir_name", ""),
        "tgs_steady": steady.get("mean") if steady else None,
        "tgs_all": tgs.get("all", {}).get("mean") if tgs.get("all") else None,
        "num_steps": _logical_steps(tgs, j.get("num_nodes")),
        "step_begin": j.get("step_begin"),
        "step_end": j.get("step_end"),
        "computation_pct": tl.get("computation_time"),
        "exposed_comm_pct": tl.get("exposed_comm_time"),
        "idle_pct": tl.get("idle_time"),
    }
    if include_per_step:
        summary["tgs_per_step"] = j.get("tgs_per_step", [])
    else:
        summary["timestamp"] = j.get("timestamp", "")
        summary["analyzed_at"] = j.get("analyzed_at", "")
        summary["has_hlo"] = bool(j.get("artifacts", {}).get("hlo_file"))
        summary["has_xplane"] = bool(j.get("artifacts", {}).get("xplane_files"))
        summary["has_tracelens"] = bool(j.get("artifacts", {}).get("tracelens_dir"))
    return summary


def _list_files_recursive(root: Path) -> list[dict]:
    """Recursively list files in a directory with sizes."""
    files = []
    for f in sorted(root.rglob("*")):
        if f.is_file():
            rel = str(f.relative_to(root))
            try:
                size = f.stat().st_size
            except OSError:
                size = 0
            files.append({"path": rel, "size": size, "name": f.name})
    return files


# ── Routes ───────────────────────────────────────────────────────────────────


@app.get("/", response_class=HTMLResponse)
async def index():
    """Serve the single-page dashboard."""
    if not DASHBOARD_HTML.is_file():
        return HTMLResponse(
            "<h1>Dashboard not found</h1>"
            f"<p>Expected at: {DASHBOARD_HTML}</p>",
            status_code=500,
        )
    return HTMLResponse(DASHBOARD_HTML.read_text())


@app.get("/api/jobs")
async def list_jobs():
    """List all analyzed jobs with summary metrics."""
    jobs = _scan_jobs()
    return [_job_summary(j) for j in jobs]


@app.get("/api/jobs/{job_id}")
async def get_job(job_id: str):
    """Full job details from analysis.json."""
    job_dir = _find_job_dir(job_id)
    data = _load_analysis(job_dir)
    data["dir_name"] = job_dir.name
    return data


@app.get("/api/jobs/{job_id}/log")
async def get_job_log(job_id: str, tail: int | None = Query(None)):
    """Return raw log file content."""
    job_dir = _find_job_dir(job_id)
    log_file = _find_log_file(job_dir)
    if not log_file or not log_file.is_file():
        raise HTTPException(404, "Log file not found")
    text = log_file.read_text(errors="replace")
    if tail:
        lines = text.splitlines()
        text = "\n".join(lines[-tail:])
    return JSONResponse({"content": text, "path": str(log_file.name)})


@app.get("/api/jobs/{job_id}/hlo")
async def get_job_hlo(
    job_id: str,
    op: str = Query("all"),
    name: bool = Query(False),
    topology: bool = Query(False),
    fusion_stats: bool = Query(False),
):
    """Run IRLens on demand with the requested flags."""
    job_dir = _find_job_dir(job_id)
    hlo_file = _find_hlo_file(job_dir)
    if not hlo_file:
        raise HTTPException(404, "No HLO dump found in xla_dump/")

    cmd = [sys.executable, str(SCRIPT_DIR / "IRLens_analyze_hlo_ir.py"), str(hlo_file)]
    if op in ("communication", "computation"):
        cmd.extend(["--op", op])
    if name:
        cmd.append("--name")
    if topology:
        cmd.append("--topology")
    if fusion_stats:
        cmd.append("--fusion-stats")

    result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
    return JSONResponse({
        "output": result.stdout,
        "stderr": result.stderr,
        "returncode": result.returncode,
        "hlo_file": hlo_file.name,
    })


def _parse_gpu_events_csv(path: Path) -> dict | None:
    """Parse gpu_events_averages.csv (rows keyed by ``type``) into a dict.

    Returns e.g. ``{"computation_time": {"time_ms": 22376.5, "percent": 74.57}, ...}``
    """
    if not path.is_file():
        return None
    try:
        result: dict = {}
        with open(path, newline="") as f:
            for row in csv.DictReader(f):
                t = row.get("type", "").strip()
                if t:
                    result[t] = {
                        "time_ms": round(float(row.get("time ms", 0)), 2),
                        "percent": round(float(row.get("percent", 0)), 2),
                    }
        return result if result else None
    except (OSError, csv.Error, ValueError):
        return None


def _parse_gpu_timeline_csv(path: Path) -> list[dict] | None:
    """Parse gpu_timeline.csv into per-GPU dicts.

    Groups rows by ``gpu_pid`` and pivots metric types into keys.
    Returns e.g. ``[{"gpu_pid": "1001", "computation_time": 75.0, ...}, ...]``
    """
    if not path.is_file():
        return None
    try:
        from collections import defaultdict
        gpus: dict = defaultdict(dict)
        with open(path, newline="") as f:
            for row in csv.DictReader(f):
                pid = row.get("gpu_pid", "")
                t = row.get("type", "").strip()
                if pid and t:
                    gpus[pid][t] = round(float(row.get("percent", 0)), 2)
                    gpus[pid]["time_ms_" + t] = round(float(row.get("time ms", 0)), 2)
        if not gpus:
            return None
        return [{"gpu_pid": pid, **vals} for pid, vals in sorted(gpus.items())]
    except (OSError, csv.Error, ValueError):
        return None


def _parse_kernel_category_csv(path: Path) -> list[dict] | None:
    """Parse kernel_launchers_summary_by_category.csv.

    Returns rows with normalised keys, already including ``time ms per gpu``.
    """
    if not path.is_file():
        return None
    try:
        rows = []
        with open(path, newline="") as f:
            for row in csv.DictReader(f):
                cat = row.get("op category", "").strip()
                if not cat:
                    continue
                rows.append({
                    "category": cat,
                    "count": int(float(row.get("Count", 0))),
                    "total_time_ms": round(float(row.get("total_direct_kernel_time_ms", 0)), 2),
                    "time_ms_per_gpu": round(float(row.get("time ms per gpu", 0)), 2),
                    "percent": round(float(row.get("Percentage (%)", 0)), 2),
                    "cumulative_percent": round(float(row.get("Cumulative Percentage (%)", 0)), 2),
                })
        return rows if rows else None
    except (OSError, csv.Error, ValueError):
        return None


@app.get("/api/jobs/{job_id}/tracelens")
async def get_job_tracelens(job_id: str):
    """Parse and return TraceLens CSV data as JSON."""
    job_dir = _find_job_dir(job_id)
    csvs_dir = job_dir / "tracelens" / "csvs"
    if not csvs_dir.is_dir():
        raise HTTPException(404, "No TraceLens data found")

    result: dict = {}

    avg = _parse_gpu_events_csv(csvs_dir / "gpu_events_averages.csv")
    if avg:
        result["gpu_averages"] = avg

    per_gpu = _parse_gpu_timeline_csv(csvs_dir / "gpu_timeline.csv")
    if per_gpu:
        result["gpu_per_gpu"] = per_gpu

    kcat = _parse_kernel_category_csv(
        csvs_dir / "kernel_launchers_summary_by_category.csv"
    )
    if kcat:
        result["kernel_category"] = kcat

    result["csv_files"] = [f.name for f in sorted(csvs_dir.glob("*.csv"))]

    return result


@app.get("/api/jobs/{job_id}/tgs-steps")
async def get_tgs_steps(job_id: str):
    """Per-step TGS values for charting."""
    job_dir = _find_job_dir(job_id)
    data = _load_analysis(job_dir)
    return {
        "tgs_per_step": data.get("tgs_per_step", []),
        "mfu_per_step": data.get("mfu_per_step", []),
        "loss_per_step": data.get("loss_per_step", []),
        "seconds_per_step": data.get("seconds_per_step", []),
        "tgs": data.get("tgs", {}),
    }


@app.get("/api/jobs/{job_id}/files")
async def list_job_files(job_id: str):
    """List all files in the job directory."""
    job_dir = _find_job_dir(job_id)
    return {"files": _list_files_recursive(job_dir)}


@app.get("/api/jobs/{job_id}/files/{file_path:path}")
async def serve_job_file(job_id: str, file_path: str):
    """Serve a specific file from the job directory."""
    job_dir = _find_job_dir(job_id)
    target = (job_dir / file_path).resolve()
    # Security: ensure the resolved path is under job_dir
    if not str(target).startswith(str(job_dir.resolve())):
        raise HTTPException(403, "Path traversal not allowed")
    if not target.is_file():
        raise HTTPException(404, f"File not found: {file_path}")
    return FileResponse(target, filename=target.name)


@app.get("/api/jobs/{job_id}/download")
async def download_job(job_id: str):
    """Stream a zip archive of the job directory."""
    job_dir = _find_job_dir(job_id)

    def generate_zip():
        buf = io.BytesIO()
        with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
            for f in job_dir.rglob("*"):
                if f.is_file():
                    arcname = f"{job_dir.name}/{f.relative_to(job_dir)}"
                    zf.write(f, arcname)
        buf.seek(0)
        yield buf.read()

    filename = f"{job_dir.name}.zip"
    return StreamingResponse(
        generate_zip(),
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@app.get("/api/compare")
async def compare_jobs(jobs: str = Query(..., description="Comma-separated job IDs")):
    """Return comparison data for multiple jobs."""
    job_ids = [j.strip() for j in jobs.split(",") if j.strip()]
    if len(job_ids) < 2:
        raise HTTPException(400, "Need at least 2 job IDs to compare")

    results = []
    for jid in job_ids:
        try:
            job_dir = _find_job_dir(jid)
            data = _load_analysis(job_dir)
            results.append(_job_summary(data, dir_name=job_dir.name, include_per_step=True))
        except HTTPException:
            results.append({"job_id": jid, "error": "not found"})

    return results


# ── CLI ──────────────────────────────────────────────────────────────────────


def main():
    import uvicorn

    parser = argparse.ArgumentParser(
        prog="perf_server",
        description="Web dashboard for MaxText job performance analysis.",
    )
    parser.add_argument(
        "--host", default="127.0.0.1",
        help="bind address (default: 127.0.0.1, use 0.0.0.0 for remote access)",
    )
    parser.add_argument(
        "--port", type=int, default=8080,
        help="port (default: 8080)",
    )
    parser.add_argument(
        "--outputs-dir",
        default=None,
        help="outputs directory (default: JOB_WORKSPACE or ../outputs)",
    )
    args = parser.parse_args()

    import os
    outputs = args.outputs_dir or os.environ.get(
        "JOB_WORKSPACE", str(SCRIPT_DIR.parent / "outputs")
    )
    configure(Path(outputs))

    print(f"Serving MaxText Perf Dashboard")
    print(f"  Outputs dir: {_outputs_dir}")
    print(f"  URL: http://{args.host}:{args.port}")
    print()

    uvicorn.run(app, host=args.host, port=args.port, log_level="info")


if __name__ == "__main__":
    main()
