#===============================================================================
# Model Architecture: DeepSeek Proxy e128-h2048
# tokenizer_path should be set to appropriate DS tokenizer

base_emb_dim: 2048
base_num_query_heads: 32
base_num_kv_heads: 8
base_num_decoder_layers: 64
head_dim: 128
mlp_activations: ["silu","linear"]
vocab_size: 102400
enable_dropout: False
logits_via_embedding: False
normalization_layer_epsilon: 1.0e-6

# **** CHANGE HERE (START) ****
base_mlp_dim: 2048
base_moe_mlp_dim: 2048
num_experts: 128
num_experts_per_tok: 2
# Use Mixtral decoder_block (instead of deepseek) and global attention (not MLA) for the Proxy
decoder_block: mixtral
attention_type: global
# **** CHANGE HERE (END) ****

# **** FOR REFERENCE ONLY, LIKELY NO CHANGE **** RoPE (Settings used by DeepSeek)
rope_type: yarn
rope_max_timescale: 10_000 # DeepSeek uses  "rope_theta": 10000
max_position_embeddings: 163840
original_max_position_embeddings: 4096
rope_factor: 40
beta_fast: 32
mscale: 0.707

# **** FOR REFERENCE ONLY ****: DeepSeek model has something like this
# decoder_block: deepseek
# attention_type: mla
# first_num_dense_layers: 0 # For DeepSeek decoder block, first_num_dense_layers: 1
# shared_experts: 0 # For DeepSeek MoE shared_experts: 2, but setting to 0
# routed_scaling_factor: 1.0
# routed_score_func: softmax
# routed_bias: False
#===============================================================================

# ── Run Config ───────────────────────────────────────────────────────────────
base_config: base.yml
run_name: ds-proxy-e128-h2048
hardware: gpu
# NOTE: inline model; omit model_name!
#model_name:

# ── Training ─────────────────────────────────────────────────────────────────
steps: 15
log_period: 100
enable_goodput_recording: False
monitor_goodput: False

# ── Parallelism ──────────────────────────────────────────────────────────────
dcn_data_parallelism: 4
dcn_fsdp_parallelism: 1
dcn_sequence_parallelism: 1 # never recommended
dcn_context_parallelism: 1
dcn_tensor_parallelism: 1 # never recommended
dcn_pipeline_parallelism: 1
dcn_expert_parallelism: 1
# At most one ICI axis can be unspecified (-1)
ici_data_parallelism: 1
ici_fsdp_parallelism: 1
ici_sequence_parallelism: 1
ici_context_parallelism: 1
ici_tensor_parallelism: 1
ici_pipeline_parallelism: 1
ici_expert_parallelism: 8

# ── Batch & Sequence ─────────────────────────────────────────────────────────
per_device_batch_size: 8
max_target_length: 4096
packing: False
# num_layers_per_pipeline_stage: 8
# num_pipeline_microbatches: 32
gradient_accumulation_steps: 1

# ── Attention & Compute ──────────────────────────────────────────────────────
attention: cudnn_flash_te
remat_policy: full
use_iota_embed: True
scan_layers: True
logits_dot_in_fp32: False
shardy: False

# ── Dtypes & Quantization ────────────────────────────────────────────────────
dtype: bfloat16
weight_dtype: float32
quantization: ""
quantize_kvcache: False
kv_quant_axis: heads_and_dkv
kv_quant_dtype: int8
checkpoint_is_quantized: False # Set to True if reading from a saved aqt quantized checkpoint

# ── MoE Runtime ──────────────────────────────────────────────────────────────
megablox: False
sparse_matmul: False
capacity_factor: 2
sharding_tolerance: 0.05
# expert_balance: True

# ── Profiler ─────────────────────────────────────────────────────────────────
profiler: "" #"xplane"
upload_all_profiler_results: true
skip_first_n_steps_for_profiler: 3
profiler_steps: 1

# ── Checkpointing ────────────────────────────────────────────────────────────
enable_checkpointing: False
async_checkpointing: False

# ── Dataset ──────────────────────────────────────────────────────────────────
dataset_type: synthetic
